### ISSUE TITLE
Asset info validation doesn't check explorer URL

### ISSUE THREAD

**Issue by unanoc** [trustwallet/assets-go-libs#13]
Fix a bug with assets/info.json validation. Explorer field is not checked with checksum (while merge-fee-bot checks it).

Example:
https://github.com/trustwallet/assets/pull/16061#issuecomment-978735985

**Comment by vikmeup** [comment]
I think check should be to make sure `id` field from `info.json` file contains inside `explorer`, case sensitive.

**Comment by unanoc** [comment]
it's fixed
