### ISSUE TITLE
List of thing to do after rewriting old logic

### ISSUE THREAD

**Issue by covain** [trustwallet/assets-go-libs#28]
- [x] Move all binance clients to go-libs

**Comment by unanoc** [comment]
- [x] Move CI logic to assets repo
- [x] Turn on linters check in workflow
- [x] Clean up the dir and file structure, clean up packages namings
- [x] Remove logic with file storing and opening, we need to store only path and pass only file path as parameter to validators (else it leads to bugs with file reading)
- [x] Edit Readme (move all values to config)
